# Generated by Django 4.2.7 on 2023-11-06 19:32

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('poc_name', models.CharField(max_length=200)),
                ('poc_phone', models.CharField(max_length=15)),
                ('poc_email', models.EmailField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('service', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('invoice_number', models.CharField(max_length=30)),
                ('narration', models.CharField(max_length=200)),
                ('payment_status', models.CharField(max_length=200)),
                ('payment_mode', models.CharField(choices=[('cash', 'Cash'), ('cheq', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI'), ('cc', 'Credit Card'), ('dc', 'Debit Card')], max_length=20)),
                ('payment_ref_number', models.CharField(max_length=50)),
                ('payment_date', models.DateTimeField(verbose_name='Paid on')),
                ('due_date', models.DateTimeField(verbose_name='Last payable by')),
                ('billed_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Date billed')),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceMgt.client')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='invoiceMgt.service')),
            ],
        ),
    ]
