# Generated by Django 4.2.7 on 2023-11-06 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('invoiceMgt', '0002_alter_invoice_payment_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invoice',
            name='narration',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_date',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Paid on'),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_mode',
            field=models.CharField(blank=True, choices=[('cash', 'Cash'), ('cheq', 'Cheque'), ('neft', 'NEFT'), ('rtgs', 'RTGS'), ('imps', 'IMPS'), ('upi', 'UPI'), ('cc', 'Credit Card'), ('dc', 'Debit Card')], max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_ref_number',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='invoice',
            name='payment_status',
            field=models.CharField(blank=True, choices=[('1', 'Received'), ('0', 'Pending')], max_length=20, null=True),
        ),
    ]
